<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>dotnet_library_api</RootNamespace>
    <UserSecretsId>a1c167d4-31d5-488b-8c65-a999a707fd6c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dotnet-library-api.Application\dotnet-library-api.Application.csproj" />
    <ProjectReference Include="..\dotnet-library-api.Infrastructure\dotnet-library-api.Infrastructure.csproj" />
  </ItemGroup>

</Project>
